#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
begin
  require 'dotenv/load'
rescue LoadError
  # Optional dependency: continue without .env loading.
end

require 'em/tools'
Em::Tools::Cli::App.start(ARGV)
